version: "3"
services:
  postgres:
    image: postgres:14
    container_name: my-postgres
    environment:
      POSTGRES_DB: my_fabric_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
