# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true

    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
        SANS:
          - network.legitifyapp.com
          - localhost
      - Hostname: orderer2
        SANS:
          - network.legitifyapp.com
          - localhost
      - Hostname: orderer3
        SANS:
          - network.legitifyapp.com
          - localhost
      - Hostname: orderer4
        SANS:
          - network.legitifyapp.com
          - localhost
