version: '3.7'

networks:
  test:
    external: true
    name: fabric_test

services:
  ca.orgnewuniversity2.com:
    image: hyperledger/fabric-ca:1.5
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orgnewuniversity2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=12054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:22054
      - FABRIC_CA_SERVER_CSR_HOSTS=ca.orgnewuniversity2.com,localhost,localhost
    ports:
      - '12054:12054'
      - '22054:22054'
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/orgnewuniversity2:/etc/hyperledger/fabric-ca-server
    container_name: ca.orgnewuniversity2.com
    networks:
      - test
