version: '3.7'

networks:
  test:
    external: true
    name: fabric_test

services:
  ca.orgnewuniversity.com:
    image: hyperledger/fabric-ca:1.5
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orgnewuniversity
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=11054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:21054
      - FABRIC_CA_SERVER_CSR_HOSTS=ca.orgnewuniversity.com,localhost,localhost
    ports:
      - '11054:11054'
      - '21054:21054'
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/orgnewuniversity:/etc/hyperledger/fabric-ca-server
    container_name: ca.orgnewuniversity.com
    networks:
      - test
