version: '3.7'

volumes:
  peer0.orgnewuniversity2.com:

networks:
  test:
    external: true
    name: fabric_test

services:
  peer0.orgnewuniversity2.com:
    container_name: peer0.orgnewuniversity2.com
    image: hyperledger/fabric-peer:2.5.10
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.orgnewuniversity2.com
      - CORE_PEER_ADDRESS=peer0.orgnewuniversity2.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.orgnewuniversity2.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgnewuniversity2.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgnewuniversity2.com:11051
      - CORE_PEER_LOCALMSPID=OrgNewUniversity2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.orgnewuniversity2.com:13051
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../organizations/peerOrganizations/orgnewuniversity2.com/peers/peer0.orgnewuniversity2.com:/etc/hyperledger/fabric
      - peer0.orgnewuniversity2.com:/var/hyperledger/production
      - ../config:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/host/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - 11051:11051
      - 11052:11052
      - 13051:13051
    networks:
      - test
