OrdererOrgs:
  - Name: Orderer
    Domain: legitify.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: UniversityOrg
    Domain: university.legitify.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
