version: "2"

networks:
  test:

services:
  orderer.legitify.com:
    container_name: orderer.legitify.com
    image: hyperledger/fabric-orderer:2.4.1
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPFILE=/etc/hyperledger/fabric/genesis.block
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../organizations/ordererOrganizations/legitify.com/orderers/orderer.legitify.com/msp:/etc/hyperledger/msp/orderer
      - ../organizations/ordererOrganizations/legitify.com/orderers/orderer.legitify.com/tls:/etc/hyperledger/tls
      - ../channel-artifacts/genesis.block:/etc/hyperledger/fabric/genesis.block
    ports:
      - "7050:7050"
    networks:
      - test
    platform: linux/amd64

  peer0.university.legitify.com:
    container_name: peer0.university.legitify.com
    image: hyperledger/fabric-peer:2.4.1
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer0.university.legitify.com
      - CORE_PEER_ADDRESS=peer0.university.legitify.com:7051
      - CORE_PEER_LOCALMSPID=UniversityMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - ../organizations/peerOrganizations/university.legitify.com/peers/peer0.university.legitify.com/msp:/etc/hyperledger/msp/peer/
      - ../organizations/peerOrganizations/university.legitify.com/peers/peer0.university.legitify.com/tls:/etc/hyperledger/tls
      - /var/run/docker.sock:/host/var/run/docker.sock
    ports:
      - "7051:7051"
      - "7052:7052"
      - "7053:7053"
    networks:
      - test
    platform: linux/amd64
