################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ../organizations/ordererOrganizations/legitifyapp.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.legitifyapp.com:7050

  - &OrgIssuer
    Name: OrgIssuer
    ID: OrgIssuerMSP
    MSPDir: ../organizations/peerOrganizations/orgissuer.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrgIssuerMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrgIssuerMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrgIssuerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrgIssuerMSP.peer')"
    AnchorPeers:
      - Host: peer0.orgissuer.com
        Port: 7051

  - &OrgVerifier
    Name: OrgVerifier
    ID: OrgVerifierMSP
    MSPDir: ../organizations/peerOrganizations/orgverifier.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrgVerifierMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrgVerifierMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrgVerifierMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrgVerifierMSP.peer')"
    AnchorPeers:
      - Host: peer0.orgverifier.com
        Port: 8051

  - &OrgHolder
    Name: OrgHolder
    ID: OrgHolderMSP
    MSPDir: ../organizations/peerOrganizations/orgholder.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrgHolderMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrgHolderMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrgHolderMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrgHolderMSP.peer')"
    AnchorPeers:
      - Host: peer0.orgholder.com
        Port: 9051

################################################################################
#
#   SECTION: Capabilities
#
################################################################################
Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true

  Orderer: &OrdererCapabilities
    V2_0: true

  Application: &ApplicationCapabilities
    V2_5: true

################################################################################
#
#   SECTION: Application
#
################################################################################

Application: &ApplicationDefaults
  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: 'ANY Readers'
    Writers:
      Type: ImplicitMeta
      Rule: 'ANY Writers'
    Admins:
      Type: ImplicitMeta
      Rule: 'MAJORITY Admins'
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: 'MAJORITY Endorsement'
    Endorsement:
      Type: ImplicitMeta
      Rule: 'MAJORITY Endorsement'
  Capabilities:
    <<: *ApplicationCapabilities

################################################################################
#
#   SECTION: Orderer
#
################################################################################
Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.legitifyapp.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: 'ANY Readers'
    Writers:
      Type: ImplicitMeta
      Rule: 'ANY Writers'
    Admins:
      Type: ImplicitMeta
      Rule: 'MAJORITY Admins'
    BlockValidation:
      Type: ImplicitMeta
      Rule: 'ANY Writers'
################################################################################
#
#   CHANNEL
#
################################################################################
Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: 'ANY Readers'
    Writers:
      Type: ImplicitMeta
      Rule: 'ANY Writers'
    Admins:
      Type: ImplicitMeta
      Rule: 'MAJORITY Admins'

  Capabilities:
    <<: *ChannelCapabilities
################################################################################
#
#   Profile
#
################################################################################
Profiles:
  ChannelUsingRaft:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      EtcdRaft:
        Consenters:
          - Host: orderer.legitifyapp.com
            Port: 7050
            ClientTLSCert: ../organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/tls/server.crt
            ServerTLSCert: ../organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/tls/server.crt
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *OrgIssuer
        - *OrgVerifier
        - *OrgHolder
      Capabilities: *ApplicationCapabilities
