OrdererOrgs:
  - Name: Orderer
    Domain: legitifyapp.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        CommonName: orderer.legitifyapp.com
        SANS:
          - orderer.legitifyapp.com
          - orderer
          - localhost

PeerOrgs:
  - Name: OrgIssuer
    Domain: orgissuer.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: OrgVerifier
    Domain: orgverifier.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: OrgHolder
    Domain: orgholder.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
