################################################################################
#
#   Orderer Configuration
#
################################################################################
General:
    ListenAddress: 0.0.0.0
    ListenPort: 7050
    TLS:
        Enabled: true
        PrivateKey: /data/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/tls/server.key
        Certificate: /data/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/tls/server.crt
        RootCAs:
          - /data/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/tls/ca.crt
        ClientAuthRequired: false
        ClientRootCAs:
    Keepalive:
        ServerMinInterval: 60s
        ServerInterval: 7200s
        ServerTimeout: 20s
    MaxRecvMsgSize: 104857600
    MaxSendMsgSize: 104857600
    Cluster:
        SendBufferSize: 10
        ClientCertificate: /data/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/tls/server.crt
        ClientPrivateKey: /data/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/tls/server.key
        ListenPort:
        ListenAddress:
        ServerCertificate:
        ServerPrivateKey:
    LocalMSPDir: /data/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/msp
    LocalMSPID: OrdererMSP
    BootstrapMethod: none
    Profile:
        Enabled: false
        Address: 0.0.0.0:6060
    BCCSP:
        Default: SW
        SW:
            Hash: SHA2
            Security: 256
            FileKeyStore:
                KeyStore:
    Authentication:
        TimeWindow: 15m

################################################################################
#
#   SECTION: File Ledger
#
################################################################################
FileLedger:
    Location: /var/hyperledger/production/orderer

################################################################################
#
#   SECTION: Kafka (deprecated, kept for compatibility)
#
################################################################################
Kafka:
    Retry:
        ShortInterval: 5s
        ShortTotal: 10m
        LongInterval: 5m
        LongTotal: 12h
        NetworkTimeouts:
            DialTimeout: 10s
            ReadTimeout: 10s
            WriteTimeout: 10s
        Metadata:
            RetryBackoff: 250ms
            RetryMax: 3
        Producer:
            RetryBackoff: 100ms
            RetryMax: 3
        Consumer:
            RetryBackoff: 2s
    Verbose: false
    TLS:
        Enabled: false

################################################################################
#
#   SECTION: Debug
#
################################################################################
Debug:
    BroadcastTraceDir:
    DeliverTraceDir:

################################################################################
#
#   SECTION: Operations
#
################################################################################
Operations:
    ListenAddress: 0.0.0.0:9443
    TLS:
        Enabled: false

################################################################################
#
#   SECTION: Metrics
#
################################################################################
Metrics:
    Provider: prometheus

################################################################################
#
#   SECTION: Admin
#
################################################################################
Admin:
    ListenAddress: 0.0.0.0:7053
    TLS:
        Enabled: true
        Certificate: /data/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/tls/server.crt
        PrivateKey: /data/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/tls/server.key
        RootCAs:
          - /data/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/tls/ca.crt
        ClientAuthRequired: true
        ClientRootCAs:
          - /data/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/tls/ca.crt

################################################################################
#
#   SECTION: Channel participation
#
################################################################################
ChannelParticipation:
    Enabled: true
    MaxRequestBodySize: 1 MB

################################################################################
#
#   SECTION: Consensus
#
################################################################################
Consensus:
    WALDir: /var/hyperledger/production/orderer/etcdraft/wal
    SnapDir: /var/hyperledger/production/orderer/etcdraft/snapshot
